-- ============================================================
-- 005_admin_delete_user_function.sql
-- Allows admins to permanently delete users. Audit records in
-- generated_numbers are preserved (user_id becomes NULL but
-- user_email stays for historical reference).
-- ============================================================

-- ── 1. Fix foreign key on generated_numbers so user deletion works
-- The existing FK doesn't have ON DELETE SET NULL, which blocks user deletion.

do $$
begin
  -- Drop the old constraint if it exists (name auto-generated by PG)
  if exists (
    select 1 from pg_constraint
    where conrelid = 'public.generated_numbers'::regclass
      and confrelid = 'auth.users'::regclass
      and contype = 'f'
  ) then
    execute (
      select 'alter table public.generated_numbers drop constraint ' || quote_ident(conname)
      from pg_constraint
      where conrelid = 'public.generated_numbers'::regclass
        and confrelid = 'auth.users'::regclass
        and contype = 'f'
      limit 1
    );
  end if;
end$$;

-- Re-create with ON DELETE SET NULL (keeps audit record, drops just the FK)
alter table public.generated_numbers
  add constraint generated_numbers_user_id_fkey
  foreign key (user_id) references auth.users(id) on delete set null;

-- ── 2. Admin delete user function ──────────────────────────────

create or replace function public.admin_delete_user(
  p_user_id uuid
)
returns json
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_caller_id  uuid;
  v_user_email text;
begin
  v_caller_id := auth.uid();

  if not exists (
    select 1 from public.profiles
    where id = v_caller_id
      and role   = 'admin'
      and status = 'active'
  ) then
    raise exception 'Not authorized: admin access required';
  end if;

  if v_caller_id = p_user_id then
    raise exception 'You cannot delete your own account';
  end if;

  select email into v_user_email
  from auth.users
  where id = p_user_id;

  if v_user_email is null then
    raise exception 'User not found';
  end if;

  -- Delete from auth.users — cascades to:
  --   - auth.identities (FK on user_id)
  --   - public.profiles (FK on id, on delete cascade)
  --   - public.generated_numbers.user_id becomes NULL (preserves audit record)
  delete from auth.users where id = p_user_id;

  return json_build_object(
    'success',          true,
    'deleted_user_id',  p_user_id,
    'deleted_email',    v_user_email
  );
end;
$$;

grant execute on function public.admin_delete_user(uuid) to authenticated;
